// @routes-hash 0b01c0bf1807fa08879c0dc53bdf6ea1
import { Express } from "express";

import route1 from "./routes/admin/credits/getCosts";
import route2 from "./routes/admin/credits/setCost";
import route3 from "./routes/admin/modelEnable/getList";
import route4 from "./routes/admin/modelEnable/setEnable";
import route5 from "./routes/admin/user/disable";
import route6 from "./routes/admin/user/invite";
import route7 from "./routes/admin/user/list";
import route8 from "./routes/admin/user/setRole";
import route9 from "./routes/agents/clearMemory";
import route10 from "./routes/agents/getMemory";
import route11 from "./routes/artStyle/addArtStyle";
import route12 from "./routes/artStyle/editArtStyle";
import route13 from "./routes/artStyle/extractStylePrompt";
import route14 from "./routes/artStyle/getArtStyle";
import route15 from "./routes/assets/addAssets";
import route16 from "./routes/assets/addAudioAssets";
import route17 from "./routes/assets/batchDelete";
import route18 from "./routes/assets/batchGenerationData";
import route19 from "./routes/assets/delAssets";
import route20 from "./routes/assets/delImage";
import route21 from "./routes/assets/getAssetsApi";
import route22 from "./routes/assets/getImage";
import route23 from "./routes/assets/getMaterialData";
import route24 from "./routes/assets/pollingImageAssets";
import route25 from "./routes/assets/pollingPromptAssets";
import route26 from "./routes/assets/saveAssets";
import route27 from "./routes/assets/updateAssets";
import route28 from "./routes/assets/updateAudioAssets";
import route29 from "./routes/assets/uploadClip";
import route30 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route31 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route32 from "./routes/assetsGenerate/cancelGenerate";
import route33 from "./routes/assetsGenerate/generateAssets";
import route34 from "./routes/assetsGenerate/polishAssetsPrompt";
import route35 from "./routes/common/getBigImage";
import route36 from "./routes/cornerScape/batchBindAudio";
import route37 from "./routes/cornerScape/getAllAssets";
import route38 from "./routes/cornerScape/pollingAudio";
import route39 from "./routes/cornerScape/updateAssetsAudio";
import route40 from "./routes/general/generalStatistics";
import route41 from "./routes/general/getCreditBalance";
import route42 from "./routes/general/getSingleProject";
import route43 from "./routes/general/updateProject";
import route44 from "./routes/login/getCurrentUser";
import route45 from "./routes/login/login";
import route46 from "./routes/login/sso";
import route47 from "./routes/modelSelect/getModelDetail";
import route48 from "./routes/modelSelect/getModelList";
import route49 from "./routes/novel/addNovel";
import route50 from "./routes/novel/batchDeleteNovel";
import route51 from "./routes/novel/delNovel";
import route52 from "./routes/novel/event/batchDeleteEvent";
import route53 from "./routes/novel/event/deletEvent";
import route54 from "./routes/novel/event/generateEvents";
import route55 from "./routes/novel/event/getEvent";
import route56 from "./routes/novel/getNovel";
import route57 from "./routes/novel/getNovelData";
import route58 from "./routes/novel/getNovelEventState";
import route59 from "./routes/novel/getNovelIndex";
import route60 from "./routes/novel/updateNovel";
import route61 from "./routes/other/deleteAllData";
import route62 from "./routes/other/getVersion";
import route63 from "./routes/production/assets/batchGenerateAssetsImage";
import route64 from "./routes/production/assets/deleteAssetsDireve";
import route65 from "./routes/production/assets/pollingImage";
import route66 from "./routes/production/assets/updateAssetsUrl";
import route67 from "./routes/production/editImage/generateFlowImage";
import route68 from "./routes/production/editImage/getImageDefaultModle";
import route69 from "./routes/production/editImage/getImageFlow";
import route70 from "./routes/production/editImage/saveImageFlow";
import route71 from "./routes/production/editImage/updateImageFlow";
import route72 from "./routes/production/editImage/uploadImage";
import route73 from "./routes/production/getFlowData";
import route74 from "./routes/production/getStoryboardData";
import route75 from "./routes/production/saveFlowData";
import route76 from "./routes/production/storyboard/addStoryboard";
import route77 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route78 from "./routes/production/storyboard/batchDelete";
import route79 from "./routes/production/storyboard/batchGenerateImage";
import route80 from "./routes/production/storyboard/downPreviewImage";
import route81 from "./routes/production/storyboard/editStoryboardInfo";
import route82 from "./routes/production/storyboard/getStoryboardData";
import route83 from "./routes/production/storyboard/pollingImage";
import route84 from "./routes/production/storyboard/previewImage";
import route85 from "./routes/production/storyboard/removeFrame";
import route86 from "./routes/production/storyboard/updateStoryboardUrl";
import route87 from "./routes/production/workbench/addTrack";
import route88 from "./routes/production/workbench/batchGeneratePrompt";
import route89 from "./routes/production/workbench/batchGenerateVideo";
import route90 from "./routes/production/workbench/checkVideoStateList";
import route91 from "./routes/production/workbench/deleteTrack";
import route92 from "./routes/production/workbench/delVideo";
import route93 from "./routes/production/workbench/generateVideo";
import route94 from "./routes/production/workbench/generateVideoPrompt";
import route95 from "./routes/production/workbench/getAudioBindAssetsList";
import route96 from "./routes/production/workbench/getFileUrl";
import route97 from "./routes/production/workbench/getGenerateData";
import route98 from "./routes/production/workbench/getVideoList";
import route99 from "./routes/production/workbench/selectVideo";
import route100 from "./routes/production/workbench/updateVideoDuration";
import route101 from "./routes/production/workbench/updateVideoPrompt";
import route102 from "./routes/project/addDirectorManual";
import route103 from "./routes/project/addProject";
import route104 from "./routes/project/addVisualManual";
import route105 from "./routes/project/deleteDirectorManual";
import route106 from "./routes/project/deleteVisualManual";
import route107 from "./routes/project/delProject";
import route108 from "./routes/project/editDirectorlManual";
import route109 from "./routes/project/editProject";
import route110 from "./routes/project/editVisualManual";
import route111 from "./routes/project/getModelDetails";
import route112 from "./routes/project/getProject";
import route113 from "./routes/project/getVisualManual";
import route114 from "./routes/project/queryDirectorManual";
import route115 from "./routes/project/visualManual";
import route116 from "./routes/script/addScript";
import route117 from "./routes/script/batchAddScript";
import route118 from "./routes/script/delScript";
import route119 from "./routes/script/exportScript";
import route120 from "./routes/script/extractAssets";
import route121 from "./routes/script/getAiRegex";
import route122 from "./routes/script/getScrptApi";
import route123 from "./routes/script/pollScriptAssets";
import route124 from "./routes/script/updateScript";
import route125 from "./routes/scriptAgent/getPlanData";
import route126 from "./routes/scriptAgent/setPlanData";
import route127 from "./routes/scriptAgent/updateData";
import route128 from "./routes/setting/about/checkUpdate";
import route129 from "./routes/setting/about/downloadApp";
import route130 from "./routes/setting/agentDeploy/agentSetKey";
import route131 from "./routes/setting/agentDeploy/deployAgentModel";
import route132 from "./routes/setting/agentDeploy/getAgentDeploy";
import route133 from "./routes/setting/agentDeploy/getAgentUseMode";
import route134 from "./routes/setting/agentDeploy/updateUseMode";
import route135 from "./routes/setting/dbConfig/clearData";
import route136 from "./routes/setting/dbConfig/clearTable";
import route137 from "./routes/setting/dbConfig/dbInfo";
import route138 from "./routes/setting/dbConfig/exportData";
import route139 from "./routes/setting/dbConfig/importData";
import route140 from "./routes/setting/dev/getSwitchAiDevTool";
import route141 from "./routes/setting/dev/updateSwitchAiDevTool";
import route142 from "./routes/setting/fileManagement/openFolder";
import route143 from "./routes/setting/getTextModel";
import route144 from "./routes/setting/loginConfig/getUser";
import route145 from "./routes/setting/loginConfig/updateUserPwd";
import route146 from "./routes/setting/memoryConfig/delAllMemory";
import route147 from "./routes/setting/memoryConfig/getMemory";
import route148 from "./routes/setting/memoryConfig/sureMemory";
import route149 from "./routes/setting/modelMap/bindingPrompt";
import route150 from "./routes/setting/modelMap/deletePrompt";
import route151 from "./routes/setting/modelMap/getImageAndVideoModel";
import route152 from "./routes/setting/modelMap/getPromptList";
import route153 from "./routes/setting/modelMap/savePrompt";
import route154 from "./routes/setting/modelMap/updatePrompt";
import route155 from "./routes/setting/promptManage/getPrompt";
import route156 from "./routes/setting/promptManage/updatePrompt";
import route157 from "./routes/setting/skillManagement/getSkillContent";
import route158 from "./routes/setting/skillManagement/getSkillList";
import route159 from "./routes/setting/skillManagement/saveSkillContent";
import route160 from "./routes/setting/vendorConfig/addVendor";
import route161 from "./routes/setting/vendorConfig/addVendorModel";
import route162 from "./routes/setting/vendorConfig/deleteVendor";
import route163 from "./routes/setting/vendorConfig/delVendorModel";
import route164 from "./routes/setting/vendorConfig/enableVendor";
import route165 from "./routes/setting/vendorConfig/getCodeByLink";
import route166 from "./routes/setting/vendorConfig/getVendorList";
import route167 from "./routes/setting/vendorConfig/modelTest";
import route168 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route169 from "./routes/setting/vendorConfig/modelTest/textTest";
import route170 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route171 from "./routes/setting/vendorConfig/updateCode";
import route172 from "./routes/setting/vendorConfig/updateVendorInputs";
import route173 from "./routes/setting/vendorConfig/upVendorModel";
import route174 from "./routes/task/getProject";
import route175 from "./routes/task/getTaskApi";
import route176 from "./routes/task/getTaskCategories";
import route177 from "./routes/task/taskDetails";
import route178 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/admin/credits/getCosts", route1);
  app.use("/api/admin/credits/setCost", route2);
  app.use("/api/admin/modelEnable/getList", route3);
  app.use("/api/admin/modelEnable/setEnable", route4);
  app.use("/api/admin/user/disable", route5);
  app.use("/api/admin/user/invite", route6);
  app.use("/api/admin/user/list", route7);
  app.use("/api/admin/user/setRole", route8);
  app.use("/api/agents/clearMemory", route9);
  app.use("/api/agents/getMemory", route10);
  app.use("/api/artStyle/addArtStyle", route11);
  app.use("/api/artStyle/editArtStyle", route12);
  app.use("/api/artStyle/extractStylePrompt", route13);
  app.use("/api/artStyle/getArtStyle", route14);
  app.use("/api/assets/addAssets", route15);
  app.use("/api/assets/addAudioAssets", route16);
  app.use("/api/assets/batchDelete", route17);
  app.use("/api/assets/batchGenerationData", route18);
  app.use("/api/assets/delAssets", route19);
  app.use("/api/assets/delImage", route20);
  app.use("/api/assets/getAssetsApi", route21);
  app.use("/api/assets/getImage", route22);
  app.use("/api/assets/getMaterialData", route23);
  app.use("/api/assets/pollingImageAssets", route24);
  app.use("/api/assets/pollingPromptAssets", route25);
  app.use("/api/assets/saveAssets", route26);
  app.use("/api/assets/updateAssets", route27);
  app.use("/api/assets/updateAudioAssets", route28);
  app.use("/api/assets/uploadClip", route29);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route30);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route31);
  app.use("/api/assetsGenerate/cancelGenerate", route32);
  app.use("/api/assetsGenerate/generateAssets", route33);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route34);
  app.use("/api/common/getBigImage", route35);
  app.use("/api/cornerScape/batchBindAudio", route36);
  app.use("/api/cornerScape/getAllAssets", route37);
  app.use("/api/cornerScape/pollingAudio", route38);
  app.use("/api/cornerScape/updateAssetsAudio", route39);
  app.use("/api/general/generalStatistics", route40);
  app.use("/api/general/getCreditBalance", route41);
  app.use("/api/general/getSingleProject", route42);
  app.use("/api/general/updateProject", route43);
  app.use("/api/login/getCurrentUser", route44);
  app.use("/api/login/login", route45);
  app.use("/api/login/sso", route46);
  app.use("/api/modelSelect/getModelDetail", route47);
  app.use("/api/modelSelect/getModelList", route48);
  app.use("/api/novel/addNovel", route49);
  app.use("/api/novel/batchDeleteNovel", route50);
  app.use("/api/novel/delNovel", route51);
  app.use("/api/novel/event/batchDeleteEvent", route52);
  app.use("/api/novel/event/deletEvent", route53);
  app.use("/api/novel/event/generateEvents", route54);
  app.use("/api/novel/event/getEvent", route55);
  app.use("/api/novel/getNovel", route56);
  app.use("/api/novel/getNovelData", route57);
  app.use("/api/novel/getNovelEventState", route58);
  app.use("/api/novel/getNovelIndex", route59);
  app.use("/api/novel/updateNovel", route60);
  app.use("/api/other/deleteAllData", route61);
  app.use("/api/other/getVersion", route62);
  app.use("/api/production/assets/batchGenerateAssetsImage", route63);
  app.use("/api/production/assets/deleteAssetsDireve", route64);
  app.use("/api/production/assets/pollingImage", route65);
  app.use("/api/production/assets/updateAssetsUrl", route66);
  app.use("/api/production/editImage/generateFlowImage", route67);
  app.use("/api/production/editImage/getImageDefaultModle", route68);
  app.use("/api/production/editImage/getImageFlow", route69);
  app.use("/api/production/editImage/saveImageFlow", route70);
  app.use("/api/production/editImage/updateImageFlow", route71);
  app.use("/api/production/editImage/uploadImage", route72);
  app.use("/api/production/getFlowData", route73);
  app.use("/api/production/getStoryboardData", route74);
  app.use("/api/production/saveFlowData", route75);
  app.use("/api/production/storyboard/addStoryboard", route76);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route77);
  app.use("/api/production/storyboard/batchDelete", route78);
  app.use("/api/production/storyboard/batchGenerateImage", route79);
  app.use("/api/production/storyboard/downPreviewImage", route80);
  app.use("/api/production/storyboard/editStoryboardInfo", route81);
  app.use("/api/production/storyboard/getStoryboardData", route82);
  app.use("/api/production/storyboard/pollingImage", route83);
  app.use("/api/production/storyboard/previewImage", route84);
  app.use("/api/production/storyboard/removeFrame", route85);
  app.use("/api/production/storyboard/updateStoryboardUrl", route86);
  app.use("/api/production/workbench/addTrack", route87);
  app.use("/api/production/workbench/batchGeneratePrompt", route88);
  app.use("/api/production/workbench/batchGenerateVideo", route89);
  app.use("/api/production/workbench/checkVideoStateList", route90);
  app.use("/api/production/workbench/deleteTrack", route91);
  app.use("/api/production/workbench/delVideo", route92);
  app.use("/api/production/workbench/generateVideo", route93);
  app.use("/api/production/workbench/generateVideoPrompt", route94);
  app.use("/api/production/workbench/getAudioBindAssetsList", route95);
  app.use("/api/production/workbench/getFileUrl", route96);
  app.use("/api/production/workbench/getGenerateData", route97);
  app.use("/api/production/workbench/getVideoList", route98);
  app.use("/api/production/workbench/selectVideo", route99);
  app.use("/api/production/workbench/updateVideoDuration", route100);
  app.use("/api/production/workbench/updateVideoPrompt", route101);
  app.use("/api/project/addDirectorManual", route102);
  app.use("/api/project/addProject", route103);
  app.use("/api/project/addVisualManual", route104);
  app.use("/api/project/deleteDirectorManual", route105);
  app.use("/api/project/deleteVisualManual", route106);
  app.use("/api/project/delProject", route107);
  app.use("/api/project/editDirectorlManual", route108);
  app.use("/api/project/editProject", route109);
  app.use("/api/project/editVisualManual", route110);
  app.use("/api/project/getModelDetails", route111);
  app.use("/api/project/getProject", route112);
  app.use("/api/project/getVisualManual", route113);
  app.use("/api/project/queryDirectorManual", route114);
  app.use("/api/project/visualManual", route115);
  app.use("/api/script/addScript", route116);
  app.use("/api/script/batchAddScript", route117);
  app.use("/api/script/delScript", route118);
  app.use("/api/script/exportScript", route119);
  app.use("/api/script/extractAssets", route120);
  app.use("/api/script/getAiRegex", route121);
  app.use("/api/script/getScrptApi", route122);
  app.use("/api/script/pollScriptAssets", route123);
  app.use("/api/script/updateScript", route124);
  app.use("/api/scriptAgent/getPlanData", route125);
  app.use("/api/scriptAgent/setPlanData", route126);
  app.use("/api/scriptAgent/updateData", route127);
  app.use("/api/setting/about/checkUpdate", route128);
  app.use("/api/setting/about/downloadApp", route129);
  app.use("/api/setting/agentDeploy/agentSetKey", route130);
  app.use("/api/setting/agentDeploy/deployAgentModel", route131);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route132);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route133);
  app.use("/api/setting/agentDeploy/updateUseMode", route134);
  app.use("/api/setting/dbConfig/clearData", route135);
  app.use("/api/setting/dbConfig/clearTable", route136);
  app.use("/api/setting/dbConfig/dbInfo", route137);
  app.use("/api/setting/dbConfig/exportData", route138);
  app.use("/api/setting/dbConfig/importData", route139);
  app.use("/api/setting/dev/getSwitchAiDevTool", route140);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route141);
  app.use("/api/setting/fileManagement/openFolder", route142);
  app.use("/api/setting/getTextModel", route143);
  app.use("/api/setting/loginConfig/getUser", route144);
  app.use("/api/setting/loginConfig/updateUserPwd", route145);
  app.use("/api/setting/memoryConfig/delAllMemory", route146);
  app.use("/api/setting/memoryConfig/getMemory", route147);
  app.use("/api/setting/memoryConfig/sureMemory", route148);
  app.use("/api/setting/modelMap/bindingPrompt", route149);
  app.use("/api/setting/modelMap/deletePrompt", route150);
  app.use("/api/setting/modelMap/getImageAndVideoModel", route151);
  app.use("/api/setting/modelMap/getPromptList", route152);
  app.use("/api/setting/modelMap/savePrompt", route153);
  app.use("/api/setting/modelMap/updatePrompt", route154);
  app.use("/api/setting/promptManage/getPrompt", route155);
  app.use("/api/setting/promptManage/updatePrompt", route156);
  app.use("/api/setting/skillManagement/getSkillContent", route157);
  app.use("/api/setting/skillManagement/getSkillList", route158);
  app.use("/api/setting/skillManagement/saveSkillContent", route159);
  app.use("/api/setting/vendorConfig/addVendor", route160);
  app.use("/api/setting/vendorConfig/addVendorModel", route161);
  app.use("/api/setting/vendorConfig/deleteVendor", route162);
  app.use("/api/setting/vendorConfig/delVendorModel", route163);
  app.use("/api/setting/vendorConfig/enableVendor", route164);
  app.use("/api/setting/vendorConfig/getCodeByLink", route165);
  app.use("/api/setting/vendorConfig/getVendorList", route166);
  app.use("/api/setting/vendorConfig/modelTest", route167);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route168);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route169);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route170);
  app.use("/api/setting/vendorConfig/updateCode", route171);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route172);
  app.use("/api/setting/vendorConfig/upVendorModel", route173);
  app.use("/api/task/getProject", route174);
  app.use("/api/task/getTaskApi", route175);
  app.use("/api/task/getTaskCategories", route176);
  app.use("/api/task/taskDetails", route177);
  app.use("/api/test/test", route178);
}
